import { MCPServerConfig, MCPTool, MCPParameter } from '../types';

function generateJsonSchema(parameters: MCPParameter[]): string {
  const properties: Record<string, any> = {};
  const required: string[] = [];

  parameters.forEach((param) => {
    properties[param.name] = {
      type: param.type === 'array' ? 'array' : param.type === 'object' ? 'object' : param.type,
      description: param.description,
    };
    
    if (param.required) {
      required.push(param.name);
    }
  });

  return JSON.stringify({
    type: 'object',
    properties,
    required,
  }, null, 2);
}

function generateToolHandler(tool: MCPTool): string {
  const paramsType = tool.parameters.length > 0 
    ? `{ ${tool.parameters.map(p => `${p.name}${p.required ? '' : '?'}: ${p.type}`).join(', ')} }`
    : '{}';

  return `
// ${tool.icon} ${tool.name} Tool
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: '${tool.name.toLowerCase().replace(/\s+/g, '_')}',
      description: '${tool.description}',
      inputSchema: ${generateJsonSchema(tool.parameters).split('\n').join('\n    ')},
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name === '${tool.name.toLowerCase().replace(/\s+/g, '_')}') {
    const args = request.params.arguments as ${paramsType};
    
    // TODO: Implement tool logic here
    return {
      content: [
        {
          type: 'text',
          text: \`Executed ${tool.name} with: \${JSON.stringify(args, null, 2)}\`,
        },
      ],
    };
  }
});`;
}

export function generateMCPServer(config: MCPServerConfig): string {
  const toolHandlers = config.tools.map(generateToolHandler).join('\n');

  return `import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

/**
 * ${config.name}
 * Version: ${config.version}
 * 
 * Generated by MCP Server Studio
 * https://mcp-server-studio.vercel.app
 */

const server = new Server(
  {
    name: '${config.name}',
    version: '${config.version}',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

${toolHandlers}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('${config.name} MCP server running on stdio');
}

main().catch((error) => {
  console.error('Server error:', error);
  process.exit(1);
});
`;
}
