import { MCPServerConfig, MCPTool, MCPParameter, MCPResource, MCPPrompt } from '../types';

/**
 * Converts a name to snake_case for identifiers
 */
function toSnakeCase(name: string): string {
  return name.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
}

/**
 * Generates parameter documentation for a tool or prompt
 */
function generateParameterDocs(parameters: MCPParameter[]): string {
  if (parameters.length === 0) {
    return '*No parameters*';
  }

  return parameters
    .map(p => {
      const requiredTag = p.required ? '**required**' : '*optional*';
      return `- \`${p.name}\` (${p.type}, ${requiredTag}): ${p.description}`;
    })
    .join('\n');
}

/**
 * Generates README.md content for the MCP server
 */
export function generateReadme(config: MCPServerConfig): string {
  const toolDocs = (config.tools || [])
    .map(tool => {
      const toolId = toSnakeCase(tool.name);
      return `### ${tool.icon} ${tool.name}

**ID:** \`${toolId}\`

${tool.description}

**Parameters:**
${generateParameterDocs(tool.parameters)}
`;
    })
    .join('\n');

  const resourceDocs = (config.resources || [])
    .map(resource => {
      return `### ${resource.name}

**URI:** \`${resource.uri}\`
**MIME Type:** \`${resource.mimeType}\`

${resource.description}
`;
    })
    .join('\n');

  const promptDocs = (config.prompts || [])
    .map(prompt => {
      const promptId = toSnakeCase(prompt.name);
      return `### ${prompt.name}

**ID:** \`${promptId}\`

${prompt.description}

**Arguments:**
${generateParameterDocs(prompt.arguments)}
`;
    })
    .join('\n');

  const hasTools = (config.tools || []).length > 0;
  const hasResources = (config.resources || []).length > 0;
  const hasPrompts = (config.prompts || []).length > 0;

  return `# ${config.name}

> MCP Server v${config.version}

Generated by [MCP Server Studio](https://mcp-server-studio.vercel.app)

## Installation

\`\`\`bash
npm install
npm run build
\`\`\`

## Configuration

Add to your \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${config.name}": {
      "command": "node",
      "args": ["${process.cwd()}/build/index.js"]
    }
  }
}
\`\`\`

Or for development:

\`\`\`json
{
  "mcpServers": {
    "${config.name}": {
      "command": "npx",
      "args": ["tsx", "${process.cwd()}/src/index.ts"]
    }
  }
}
\`\`\`

${hasTools ? `## Available Tools

${toolDocs}` : ''}

${hasResources ? `## Available Resources

${resourceDocs}` : ''}

${hasPrompts ? `## Available Prompts

${promptDocs}` : ''}

## Development

\`\`\`bash
# Watch mode for development
npm run dev

# Build for production
npm run build

# Run the server
npm start
\`\`\`

## Testing

Use the [MCP Inspector](https://github.com/modelcontextprotocol/inspector) to test your server:

\`\`\`bash
npx @modelcontextprotocol/inspector node build/index.js
\`\`\`

## License

MIT
`;
}

/**
 * Generates the claude_desktop_config.json snippet
 */
export function generateClaudeDesktopConfig(config: MCPServerConfig): string {
  const configObj = {
    mcpServers: {
      [config.name]: {
        command: 'node',
        args: ['./build/index.js'],
      },
    },
  };

  return JSON.stringify(configObj, null, 2);
}

/**
 * Generates package.json for the MCP server
 */
export function generatePackageJson(config: MCPServerConfig): string {
  const packageObj = {
    name: config.name,
    version: config.version,
    description: `MCP Server: ${config.name}`,
    type: 'module',
    main: './build/index.js',
    bin: {
      [config.name]: './build/index.js',
    },
    scripts: {
      build: 'tsc && chmod +x build/index.js',
      start: 'node build/index.js',
      dev: 'tsx watch src/index.ts',
      lint: 'eslint src/',
      test: 'node --test',
    },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.2.0',
      zod: '^3.24.0',
    },
    devDependencies: {
      '@types/node': '^20.17.0',
      typescript: '^5.7.0',
      tsx: '^4.19.0',
      eslint: '^9.0.0',
    },
    engines: {
      node: '>=18.0.0',
    },
    keywords: ['mcp', 'model-context-protocol', 'ai', 'llm'],
    license: 'MIT',
  };

  return JSON.stringify(packageObj, null, 2);
}

/**
 * Generates tsconfig.json for the MCP server
 */
export function generateTsConfig(): string {
  const tsconfigObj = {
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      outDir: './build',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      declaration: true,
      declarationMap: true,
      sourceMap: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'build'],
  };

  return JSON.stringify(tsconfigObj, null, 2);
}

/**
 * Generates all project files as a record
 */
export function generateProjectFiles(config: MCPServerConfig): Record<string, string> {
  return {
    'README.md': generateReadme(config),
    'package.json': generatePackageJson(config),
    'tsconfig.json': generateTsConfig(),
    'claude_desktop_config.json': generateClaudeDesktopConfig(config),
  };
}
